title: Sebs Ghost's Homepage
page-top-title: Sebs Ghost
top-section-bg-text: Active vision is all you need.

site_name: "Xian Huang"
site_description: "Mechanical Engineer | Robotics Enthusiast"
email: "hx2020@sjtu.edu.cn"

home-subtitle: Xianhuang&ensp;|&ensp;Sebs Ghost
copyright-text: '&copy; Sebs Ghost 2025-2030. All Rights Reserved.'
